services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  express-app:
    build: .
    container_name: express-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/test
      - PORT=3000
    depends_on:
      - mongo

volumes:
  mongo_data:
